name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/"
      - "tests/"
      - "pyproject.toml"
      - "README.md"
      - ".github/**"
  push:
    branches: [ main ]
    paths:
      - "src/"
      - "tests/"
      - "pyproject.toml"
      - "README.md"
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_PERF_TESTS: 1
      PYTHONWARNINGS: default
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run checks
        run: |
          ruff check .
          black --check .
          mypy .
          pytest -q
