name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - "src/"
      - "tests/"
      - "pyproject.toml"
      - "README.md"
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.11", "3.12"]
    env:
      SKIP_PERF_TESTS: 1
      PYTHONWARNINGS: default
      PYTHONPATH: ${{ github.workspace }}
      NO_COLOR: 1
      RICH_DISABLE_NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ runner.os == 'Windows' && 'C:\\Users\\runneradmin\\AppData\\Local\\pip\\Cache' || '~/.cache/pip' }}
          key: pip-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install dependencies
        run: pip install -e .[dev,addresses]
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Mypy
        run: mypy .
      - name: Pytest
        run: pytest -q --cov=redactor --cov-report=xml
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python }}
          path: coverage.xml
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.os }}-${{ matrix.python }}
          path: report/
          if-no-files-found: ignore
